# Generated by Django 3.2.9 on 2021-12-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRepipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MockGunDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=512)),
                ('require_tls', models.BooleanField(default=False)),
                ('skip_verification', models.BooleanField(default=True)),
                ('type', models.CharField(default='sandbox', max_length=512)),
                ('smtp_login', models.CharField(default='postmaster@samples.mockgun.org', max_length=512)),
                ('web_prefix', models.CharField(default='email', max_length=512)),
                ('web_scheme', models.CharField(default='http', max_length=10)),
                ('wildcard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('version', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MockGunMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=512)),
                ('text', models.TextField()),
                ('html', models.TextField()),
                ('tag', models.CharField(max_length=512)),
                ('bcc', models.ManyToManyField(related_name='bcc', to='main_app.EmailRepipient')),
                ('cc', models.ManyToManyField(related_name='cc', to='main_app.EmailRepipient')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.template')),
                ('to', models.ManyToManyField(related_name='to', to='main_app.EmailRepipient')),
            ],
        ),
    ]
